macOS Sonoma fixes

diff --git a/src/tm-cleanup.sh.in b/src/tm-cleanup.sh.in
--- a/src/tm-cleanup.sh.in
+++ b/src/tm-cleanup.sh.in
@@ -174,7 +174,7 @@ process_by_days()
 
         if (( ${DRY_RUN} == 0 ))
         then
-          tmutil delete ${i}
+          tmutil delete -t ${i} -d "$MACHINE_DIR"
         fi
       else
         print -- "${TM_DATE} will not be deleted because it is the latest available Time Machine snapshot."
@@ -205,7 +205,7 @@ process_by_backups()
 
       if (( ${DRY_RUN} == 0 ))
       then
-        tmutil delete ${TM_BACKUPS[i]}
+        tmutil delete -t ${TM_BACKUPS[i]} -d "$MACHINE_DIR"
       fi
     else
       print -- "${TM_DATE} will not be deleted because it is the latest available Time Machine snapshot."
@@ -217,6 +217,12 @@ tm_health_checks()
 {
   tm_check_required_programs
 
+  MACHINE_DIR=$(tmutil machinedirectory)
+  if [[ -z "$MACHINE_DIR" ]]; then
+    echo "failed to set the machine directory for tmutil"
+    exit 3
+  fi
+
   (( $# == 0 )) || {
     >&2 print -- "No arguments are allowed."
     exit 2
@@ -226,6 +232,13 @@ tm_health_checks()
     >&2 print -- "This command must be executed with super user privileges."
     exit 1
   }
+
+  if (( ${FORCE_EXECUTION} == 0 )); then
+    if tmutil status | grep -E -q 'Starting|PreparingSourceVolumes|FindingChanges|Copying|ThinningPostBackup'; then
+      print -- "A Time Machine backup is being performed. Skipping execution." >&2
+      exit 4
+    fi
+  fi
 
   # Check if a backup is running and if it is, skip execution.
   # This check relies on the undocumented tmutil `status' verb.
@@ -259,7 +272,7 @@ tm_load_backups()
   # Get the full list of backups from tmutil
   if TMUTIL_OUTPUT=$(tmutil listbackups 2> ${TM_ERR_TEMP_FILE})
   then
-    TM_BACKUPS=( "${(ps:\n:)$(tmutil listbackups)}" )
+    TM_BACKUPS=( "${(ps:\n:)$(tmutil listbackups -t)}" )
 
     # We are sorting the output of tmutil listbackups because its documentation
     # states nowhere that the output is sorted in any way.
@@ -318,6 +331,7 @@ tm_delete_backups()
   {
     for ((i = 1 ; i <= ${#backup_idx_to_delete} ; i += 1))
     do
+      # TODO: needs to be updated for macOS Sonoma 
       if ! tmutil delete ${TM_BACKUPS[${i}]} 2> ${TM_ERR_TEMP_FILE}
       then
         tm_show_last_error
